[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
zex_assetman_sol = "7KNvnNe6sMAVRwXijVeEJ3qn8ACLMcZT3gQQ76VPoKDN"

[workspace]
members = ["programs/zex-assetman-sol"]

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/sadegh/.config/solana/id.json"

[scripts]
test = "npx ts-node tests/zex-assetman-sol.ts"
test-mocha = "npx run ts-mocha -- -p ./tsconfig.json -t 1000000 tests/**/*.ts"
